services:
  gopher:
    image: oven/bun:latest
    user: "1000:1000" # Uses your host User ID and Group ID
    ports:
      - "3030:3030"  # [Host Port] : [Container Port]
    volumes:
      - .:/app  # This is the magic "Bind Mount"
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: bun run --watch src/index.ts # Bun's built-in watcher!